<a href="https://colab.research.google.com/github/teeshadembla/StockPricePred/blob/main/ANN_projectML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.18.0'

## Part 1 - Data Preprocessing

In [7]:
sample_data = pd.read_excel('Folds5x2_pp.xlsx')
X = sample_data.iloc[:, :-1].values
y = sample_data.iloc[:,-1].values
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Importing the dataset

### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size= 0.2, random_state=0)
print(X_test)
print(X_train)
print(y_test)
print(y_train)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[431.23 460.01 461.14 ... 473.26 438.   463.28]
[473.93 467.87 431.97 ... 459.01 462.72 428.12]


## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
#this ann must be initialized as a sequence of layers, input layer, 1st hidden layer, 2nd hidden layer and output layer
#using tensorflow's sequential class
#keras is now a sub library of tensor flow

ann = tf.keras.models.Sequential() #keras sublibrary, models module and Sequential class
# skeleton of the neural network is made

### Adding the input layer and the first hidden layer

In [10]:
#units is the number of neurons, we don't need to ass it, it can automatically recognized for the input layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#dense is for the connection bw the input layer and the hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

### Adding the output layer

In [12]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [13]:
#optimizer is the tool that will allow us to perform stochastic gradient descent
# loss attribute - least cost function that needs to be minimized
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [14]:
ann.fit(X_train, y_train, batch_size= 32 ,epochs=100)
#the features that are forward propagated come in batches, this is the batch size that we choose
#in the parameters above


Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2459.4917
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 676.6105
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 553.9285
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 427.0195
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 330.4265
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 257.3982
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 192.0897
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 143.0282
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 102.0902
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 75.9739
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53.5477
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41.3306
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33.2579
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.9093
Epoch 15/100
240/24

### Predicting the results of the Test set

In [16]:
#training to inference
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)), 1 ))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[431.23 430.76]
 [460.01 461.78]
 [461.14 465.26]
 ...
 [473.26 472.52]
 [438.   439.31]
 [463.28 458.52]]
